'use strict';

steps.endRulesRetention = exports;

exports.itFillDealMandatoryFieldsContractPeriod = steps.createDealContractPeriod.itFillDealMandatoryFieldsContractPeriod;
exports.checkEndRulesTooltipTextValue = steps.createDealContractPeriod.checkEndRulesTooltipTextValue;
exports.checkRulesForEndDateDataTooltipTextEndRules = steps.createDealContractPeriod.checkRulesForEndDateDataTooltipTextEndRules;
exports.checkSummaryOfRulesForEndDateTitleTextEndRules = steps.createDealContractPeriod.checkSummaryOfRulesForEndDateTitleTextEndRules;
exports.checkSummaryOfRulesForEndDateDataTooltipTextEndRules = steps.createDealContractPeriod.checkSummaryOfRulesForEndDateDataTooltipTextEndRules;
exports.checkRulesTitleTextEndRules = steps.createDealContractPeriod.checkRulesTitleTextEndRules;
exports.checkRulesDataTooltipTextEndRules = steps.createDealContractPeriod.checkRulesDataTooltipTextEndRules;
exports.checkEndDateDataTooltipTextEndRules = steps.createDealContractPeriod.checkEndDateDataTooltipTextEndRules;
exports.checkAccountingPeriodEndDataTooltipTextEndRules = steps.createDealContractPeriod.checkAccountingPeriodEndDataTooltipTextEndRules;
exports.checkVariableLeftDataTooltipTextEndRules = steps.createDealContractPeriod.checkVariableLeftDataTooltipTextEndRules;
exports.checkAttributeLeftDataTooltipTextEndRules = steps.createDealContractPeriod.checkAttributeLeftDataTooltipTextEndRules;
exports.checkWithNoticeDataTooltipTextEndRules = steps.createDealContractPeriod.checkWithNoticeDataTooltipTextEndRules;
exports.checkRequirementDataTooltipTextEndRules = steps.createDealContractPeriod.checkRequirementDataTooltipTextEndRules;
exports.checkVariableRightDataTooltipTextEndRules = steps.createDealContractPeriod.checkVariableRightDataTooltipTextEndRules;
exports.checkAttributeRightDataTooltipTextEndRules = steps.createDealContractPeriod.checkAttributeRightDataTooltipTextEndRules;
exports.selectEndDateEndRulesSpecificValueRuleNumberI = steps.createDealContractPeriod.selectEndDateEndRulesSpecificValueRuleNumberI;
exports.validateAccountingPeriodEndRulesIsDisplayed = steps.createDealContractPeriod.validateAccountingPeriodEndRulesIsDisplayed;
exports.validatePreDefinedDateFieldEndRulesIsRequiredWarning = steps.createDealContractPeriod.validatePreDefinedDateFieldEndRulesIsRequiredWarning;
exports.fillIntoPreDefinedDateFieldEndRulesSpecificDateRuleNumberI = steps.createDealContractPeriod.fillIntoPreDefinedDateFieldEndRulesSpecificDateRuleNumberI;
exports.validateOffsetByInputFieldEndRulesIsDisplayed = steps.createDealContractPeriod.validateOffsetByInputFieldEndRulesIsDisplayed;
exports.fillIntoOffsetByInputFieldEndRulesRuleNumberI = steps.createDealContractPeriod.fillIntoOffsetByInputFieldEndRulesRuleNumberI;
exports.selectRandomOptionFromOffsetByChoiceEndRules = steps.createDealContractPeriod.selectRandomOptionFromOffsetByChoiceEndRules;
exports.selectWhenVariableLeftEndRulesSpecificValueRuleNumberIRowNumberJ = steps.createDealContractPeriod.selectWhenVariableLeftEndRulesSpecificValueRuleNumberIRowNumberJ;
exports.checkAttributeLeftWarningMessageEndRules = steps.createDealContractPeriod.checkAttributeLeftWarningMessageEndRules;
exports.fillIntoAttributeLeftPercentEndRulesSpecificValueRuleNumberIRowNumberJ = steps.createDealContractPeriod.fillIntoAttributeLeftPercentEndRulesSpecificValueRuleNumberIRowNumberJ;
exports.checkVariableRightWarningMessageEndRules = steps.createDealContractPeriod.checkVariableRightWarningMessageEndRules;
exports.selectRightVariableEndRulesSpecificValueRuleNumberIRowNumberJ = steps.createDealContractPeriod.selectRightVariableEndRulesSpecificValueRuleNumberIRowNumberJ;
exports.fillIntoAttributeRightEndRulesSpecificValueRuleNumberIRowNumberJ = steps.createDealContractPeriod.fillIntoAttributeRightEndRulesSpecificValueRuleNumberIRowNumberJ;
exports.validatePreDefinedDateFieldAttributeRightEndRulesIsRequiredWarning = steps.createDealContractPeriod.validatePreDefinedDateFieldAttributeRightEndRulesIsRequiredWarning;
exports.selectRequirementEndRulesSpecificValueByIndexRuleNumberIRowNumberJ = steps.createDealContractPeriod.selectRequirementEndRulesSpecificValueByIndexRuleNumberIRowNumberJ;
exports.checkTextRuleWhenOrAndEndRulesRuleNumberI = steps.createDealContractPeriod.checkTextRuleWhenOrAndEndRulesRuleNumberI;
exports.clickOnAddNewRuleEndRulesAddedRuleNumberI = steps.createDealContractPeriod.clickOnAddNewRuleEndRulesAddedRuleNumberI; 
exports.checkDeleteIconIsPresentAndDataTooltipEndRulesConditionNumberIRowNumberJ = steps.createDealContractPeriod.checkDeleteIconIsPresentAndDataTooltipEndRulesConditionNumberIRowNumberJ;
exports.deleteEndRulesConditionNumberIRowNumberJ = steps.createDealContractPeriod.deleteEndRulesConditionNumberIRowNumberJ;
exports.clickOnConfirmDeleteEndRuleCondition = steps.createDealContractPeriod.clickOnConfirmDeleteEndRuleCondition;
exports.clickOnWithNoticeCheckBoxEndRulesRuleNumberIRowNumberJ = steps.createDealContractPeriod.clickOnWithNoticeCheckBoxEndRulesRuleNumberIRowNumberJ;
exports.cancelDeleteEndRules = steps.createDealContractPeriod.cancelDeleteEndRules;
exports.clickOnAddEndRulesToContractPeriod = steps.createDealContractPeriod.clickOnAddEndRulesToContractPeriod;
exports.deleteEndRule = steps.createDealContractPeriod.deleteEndRule;
exports.confirmDeleteEndRule = steps.createDealContractPeriod.confirmDeleteEndRule;
exports.cancelDeleteEntireEndRules = steps.createDealContractPeriod.cancelDeleteEntireEndRules;
exports.confirmDeleteEntireEndRules = steps.createDealContractPeriod.confirmDeleteEntireEndRules;
exports.checkSummaryTextForEndRulesRuleNumberIContainsText = steps.createDealContractPeriod.checkSummaryTextForEndRulesRuleNumberIContainsText;
exports.clickOnConfirmCancellationEndRulesModalButton = steps.createDealContractPeriod.clickOnConfirmCancellationEndRulesModalButton;
exports.selectAttributeLeftEndRulesSpecificOptionPercentOrAmountRuleNumberIRowNumberJ = steps.createDealContractPeriod.selectAttributeLeftEndRulesSpecificOptionPercentOrAmountRuleNumberIRowNumberJ;
exports.fillIntoAttributeLeftAmountEndRulesSpecificValueRuleNumberIRowNumberJ = steps.createDealContractPeriod.fillIntoAttributeLeftAmountEndRulesSpecificValueRuleNumberIRowNumberJ;
exports.checkSummaryTextForEndRulesRuleNumberI = steps.createDealContractPeriod.checkSummaryTextForEndRulesRuleNumberI;
exports.clickOnEndRulesArea = steps.createDealContractPeriod.clickOnEndRulesArea;
exports.fillIntoEndDateTypePreDefinedDateInputFieldEndRules = steps.createDealContractPeriod.fillIntoEndDateTypePreDefinedDateInputFieldEndRules;
exports.fillIntoOffsetByInputFieldEndRulesSpecificValue = steps.createDealContractPeriod.fillIntoOffsetByInputFieldEndRulesSpecificValue;
exports.selectSpecificOptionFromOffsetByChoiceEndRules = steps.createDealContractPeriod.selectSpecificOptionFromOffsetByChoiceEndRules;
exports.clickAccountingPeriodEndDateCheckBoxEndRules = steps.createDealContractPeriod.clickAccountingPeriodEndDateCheckBoxEndRules;
exports.clickOnAddRuleInTheBottomOfEndRulesForm = steps.createDealContractPeriod.clickOnAddRuleInTheBottomOfEndRulesForm;
exports.reorderEndRule = steps.createDealContractPeriod.reorderEndRule;
exports.doneEndRules = steps.createDealContractPeriod.doneEndRules;

exports.saveEndRulesForm = function () {
    it('Save the end rules', function () {
        pages.endRulesRetention.saveEndRules();
    });
};

exports.clickOnDeleteEndRulesButton = function(){
    it('Click on the delete entire end rules button', function(){
        pages.endRulesRetention.clickOnDeleteEndRulesButton();
    });
};

exports.clickOnCancelEndRulesButton = function () {
    it("Click on the cancel end rules button", function () {
        pages.endRulesRetention.clickOnCancelEndRulesButton();
    });
};
