<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Done_1</name>
   <tag></tag>
   <elementGuidId>2714c8ba-773e-4795-856b-2709b2da6c95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>{ disabled: (!activeScope.isInState('freshlyAdded') &amp;&amp; (ratesSetsForm.$invalid || contractualRateSetsModel.isInState('invalid'))) }</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>(activeScope.isInState('freshlyAdded') || ratesSetsForm.$valid) &amp;&amp; onRateSetsSave(ratesSetsForm)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SUB-VIEWS&quot;)/div[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/tg-sticky-headers[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;create-deal-wizard ng-scope&quot;]/form[@class=&quot;form-horizontal ng-dirty ng-submitted ng-valid-parse ng-valid-tags-required ng-valid-required ng-valid-rate-set-has-rates ng-valid-maxlength ng-valid-year ng-valid-month ng-valid-day-range ng-valid-date ng-valid-min ng-valid-rate-percentage-exeeds-limit ng-valid-is-i-c-r-lesser ng-valid-is-i-c-r-zero ng-valid-is-any-determines-i-c-r-yes ng-valid-rates-have-errors ng-valid ng-valid-is-ram-defined&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;deal-terms ng-scope ng-dirty ng-valid-parse ng-valid-tags-required ng-valid-required ng-valid-rate-set-has-rates ng-valid-maxlength ng-valid-year ng-valid-month ng-valid-day-range ng-valid-date ng-valid-min ng-valid-rate-percentage-exeeds-limit ng-valid-is-i-c-r-lesser ng-valid-is-i-c-r-zero ng-valid-is-any-determines-i-c-r-yes ng-valid-rates-have-errors ng-valid ng-valid-is-ram-defined&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span6 column js-details-column&quot;]/tg-view[@class=&quot;ng-scope&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;FORM DETAIL ng-scope ng-dirty ng-valid-parse ng-valid-tags-required ng-valid-required ng-valid-rate-set-has-rates ng-valid-maxlength ng-valid-year ng-valid-month ng-valid-day-range ng-valid-date ng-valid-min ng-valid-rate-percentage-exeeds-limit ng-valid-is-i-c-r-lesser ng-valid-is-i-c-r-zero ng-valid-is-any-determines-i-c-r-yes ng-valid-rates-have-errors ng-valid ng-valid-is-ram-defined&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;rate-sets-padd ng-scope&quot;]/div[@class=&quot;span12 rate-sets-container modular-edit ng-scope create ng-valid-rate-set-has-rates ng-valid-required ng-valid-maxlength ng-valid-year ng-valid-month ng-valid-day-range ng-valid-date ng-valid-min ng-valid-rate-percentage-exeeds-limit ng-valid-is-i-c-r-lesser ng-valid-is-i-c-r-zero ng-valid-tags-required ng-dirty ng-valid-parse ng-valid-is-any-determines-i-c-r-yes ng-valid ng-valid-is-ram-defined&quot;]/div[@class=&quot;rate-sets-container-inner ng-scope ng-valid-rate-set-has-rates ng-valid-required ng-valid-maxlength ng-valid-year ng-valid-month ng-valid-day-range ng-valid-date ng-valid-min ng-valid-rate-percentage-exeeds-limit ng-valid-is-i-c-r-lesser ng-valid-is-i-c-r-zero ng-valid-tags-required ng-dirty ng-valid-parse ng-valid-is-any-determines-i-c-r-yes ng-valid ng-valid-is-ram-defined&quot;]/div[@class=&quot;form-horizontal ng-scope&quot;]/div[@class=&quot;modular-container clearfix&quot;]/div[@class=&quot;rate-sets-top-toolbar sticky-top&quot;]/button[@class=&quot;btn btn-primary pull-right ng-binding&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//button[@type='button'])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='SUB-VIEWS']/div[2]/ui-view/tg-sticky-headers/div[2]/form/div/div/div[2]/div[2]/tg-view/div/div/div/div[5]/div/div/div/div/div/div[2]/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Royalty Rate Set'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRWC'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Rate Set'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[2]/preceding::button[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/button</value>
   </webElementXpaths>
</WebElementEntity>
