<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PSS_E</name>
   <tag></tag>
   <elementGuidId>ab9dc98c-3267-468f-bdcd-f109964d4e3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deal-publisher > div.ng-pristine.ng-valid.ng-valid-required > div > div > div.publisher-share.clearfix > div:nth-child(3) > div.control-group.pull-left.ps-name.relative.ng-scope.error > div > div > div > div > div:nth-child(1) > div > div.tg-typeahead__input-wrap > input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tg-typeahead__input ng-untouched ng-valid ng-dirty ng-valid-parse ng-animate ng-valid-parse-remove</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-placeholder</name>
      <type>Main</type>
      <value>{{$getPlaceholder()}}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$term</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>$isDisabled()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by Name or IPI Number ...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deal-publisher&quot;)/div[@class=&quot;ng-dirty ng-valid-parse ng-invalid ng-invalid-required ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;control-group nomargins ng-dirty ng-valid-parse ng-invalid ng-invalid-required ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;publisher-share clearfix&quot;]/div[@class=&quot;publisher-row clearfix ng-scope am-share&quot;]/div[@class=&quot;control-group pull-left ps-name relative ng-scope&quot;]/div[@class=&quot;ng-isolate-scope&quot;]/div[@class=&quot;ng-untouched ng-isolate-scope ng-dirty ng-invalid ng-invalid-required ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-parse-add ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;tg-typeahead ng-scope&quot;]/div[1]/div[@class=&quot;tg-typeahead__input-container ng-scope&quot;]/div[@class=&quot;tg-typeahead__input-wrap&quot;]/input[@class=&quot;tg-typeahead__input ng-untouched ng-valid ng-dirty ng-valid-parse ng-animate ng-valid-parse-remove&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>(//input[@type='text'])[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='deal-publisher']/div[3]/div/div/div[2]/div[4]/div[2]/div/div/div/div/div/div/div[2]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove All'])[5]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AM'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='—'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='%'])[3]/preceding::input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[4]/div[2]/div/div/div/div/div/div/div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
