<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End (Target)_targetEndDu</name>
   <tag></tag>
   <elementGuidId>f308bc53-c123-46d2-b085-b407153ee19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='targetEndDuration']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>targetEndDuration</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span1 ng-pristine ng-untouched ng-valid-ng-min ng-invalid ng-invalid-required ng-valid-maxlength ng-animate ng-pristine-remove ng-invalid-remove ng-invalid-required-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>tgModularEditModel.targetDuration</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>!tgModularEditModel.actualEndDate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-min</name>
      <type>Main</type>
      <value>1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SUB-VIEWS&quot;)/div[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/tg-sticky-headers[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;create-deal-wizard ng-scope&quot;]/form[@class=&quot;form-horizontal ng-dirty ng-submitted ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ng-min ng-valid-parse ng-valid-year ng-valid-month ng-valid-min ng-valid-date ng-valid-day-range ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;deal-terms ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ng-min ng-dirty ng-valid-parse ng-valid-year ng-valid-month ng-valid-min ng-valid-date ng-valid-day-range ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;span6 column js-details-column&quot;]/tg-view[@class=&quot;ng-scope&quot;]/div[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;details FORM DETAIL ng-scope&quot;]/div[1]/div[1]/div[@class=&quot;section&quot;]/div[@class=&quot;EDITOR modular-edit ng-scope create ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ng-min ng-dirty ng-valid-parse ng-valid-year ng-valid-month ng-valid-min ng-valid-date ng-valid-day-range ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;form-horizontal ng-scope&quot;]/div[@class=&quot;modular-container clearfix&quot;]/div[@class=&quot;ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-ng-min ng-dirty ng-valid-parse ng-valid-year ng-valid-month ng-valid-min ng-valid-date ng-valid-day-range ng-animate ng-invalid-remove ng-invalid-required-remove ng-valid-add ng-valid-required-add&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;control-group ng-scope&quot;]/div[@class=&quot;span2 controls&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;input-append&quot;]/input[@class=&quot;span1 ng-pristine ng-untouched ng-valid-ng-min ng-invalid ng-invalid-required ng-valid-maxlength ng-animate ng-pristine-remove ng-invalid-remove ng-invalid-required-remove ng-dirty-add ng-valid-parse-add ng-valid-add ng-valid-required-add&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//input[@name='targetEndDuration']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='SUB-VIEWS']/div[2]/ui-view/tg-sticky-headers/div[2]/form/div/div/div[2]/div[2]/tg-view/div/div/div/div/div/div/div[2]/div[2]/div/div/div/div/div[6]/div/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='End (Target):'])[1]/following::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start (Actual):'])[1]/following::input[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='months'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='= (2016-06-30)'])[1]/preceding::input[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[6]/div/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
