'use strict';

var pages_path = _tf_config._system_.path_to_pages,
    steps_path = _tf_config._system_.path_to_steps,
    random = require('../helpers/random'),
    randomId = random.id.makeMemoizedGenerator();

require(steps_path + 'login');
require(steps_path + 'new_work');

var beforeFeature = [
        [steps.login.itLogin]
    ],
    feature = [
        {
            name: 'Create persons to use as creators for COS and MED composite work',
            tags: ['dbg'],
            steps: function() {
                _.times(3, function(i) {
                    steps.person.useBlankPersonSlot(i);

                    steps.newPerson.goToNewPersonPage();

                    steps.newPerson.enterLastName(
                        'TEST PERSON ' + (i + 1) + ' ' + randomId('person' + i)
                    );

                    steps.newPerson.enterAffiliatedSocietySearchTerms('ASCAP');
                    steps.newPerson.selectAffiliatedSocietySearchResultByIndex(0);

                    steps.newPerson.save();

                    steps.person.findInternalIpiNumber();
               });
            }
        },
        {
            name: 'Define a COS composite work with shell works',
            tags: [],
            steps: [
                [steps.base.useBlankEntityDataSlot, ['work', 0]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(0)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Composite of Samples']],
                [steps.new_work.selectCreatorFromPersonSlot, [0, 0]],
                [steps.new_work.enterCreatorContribution, [0, 50]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(0)]],
                [steps.new_work.ensureTotalContributionTooLowMessageIsDisplayed],
                [steps.new_work.enterComponentWorkAllocation, [0, 50]],
                [steps.new_work.validateTotalContribution],
                [steps.new_work.validateDefaultShellWorkTitleLanguage, [0]],
                [steps.new_work.expectShellWorkTitleToMatchEnteredOne, [0]],
                [steps.new_work.validateDefaultShellWorkCreatorRole, [0, 0]],
                [steps.new_work.validateRequiredShellWorkCreatorNameField, [0, 0]],
                [steps.new_work.selectShellWorkCreatorFromPersonSlot, [0, 0, 0]],
                [steps.new_work.validateRequiredShellWorkCreatorContributionField, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],

                [steps.work.searchForPreviouslyEnteredComponentWork, [0]],
                [steps.work.expectNoResultsForWorkSearchMessageToBeDisplayed],
            ]
        },
        {
            name: 'Define a POT composite work with shell works',
            tags: [],
            steps: [
                [steps.base.useBlankEntityDataSlot, ['work', 1]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(1)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Potpourri']],
                [steps.new_work.selectRandomCreator, [0]],
                [steps.new_work.enterCreatorContribution, [0, 50]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(1)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 50]],
                [steps.new_work.selectRandomShellWorkCreator, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
            ]
        },
        {
            name: 'Define a UCO composite work with shell works',
            tags: [],
            steps: [
                [steps.base.useBlankEntityDataSlot, ['work', 2]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(2)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Unspecified Composite']],
                [steps.new_work.selectRandomCreator, [0]],
                [steps.new_work.enterCreatorContribution, [0, 50]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(2)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 50]],
                [steps.new_work.selectRandomShellWorkCreator, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
            ]
        },
        {
            name: 'Define a MED composite work with shell works',
            tags: [],
            steps: [
                [steps.base.useBlankEntityDataSlot, ['work', 3]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(3)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Medley']],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(3.1)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 50]],
                [steps.new_work.selectShellWorkCreatorFromPersonSlot, [0, 0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.enterNewShellWork, [1, 'TEST SHELL WORK ' + randomId(3.2)]],
                [steps.new_work.enterComponentWorkAllocation, [1, 50]],
                [steps.new_work.selectShellWorkCreatorFromPersonSlot, [1, 0, 1]],
                [steps.new_work.enterShellWorkCreatorContribution, [1, 0, 100]],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
                [steps.work.validateComponentWorkId, [1]],
                [steps.work.validateComponentWorkName, [1]],
                [steps.work.validateComponentWorkAllocation, [1]],
                [steps.work.clickShowComponentWorkDetailsButton, [1]],
                [steps.work.validateShellWorkCreatorName, [1, 0]],
                [steps.work.validateShellWorkCreatorContribution, [1, 0]],
            ]
        },
        {
            name: 'Define COS composites with multiple shell works and different allocation combinations',
            tags: [],
            steps: [
                [steps.base.useBlankEntityDataSlot, ['work', 4]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(4)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Composite of Samples']],
                [steps.new_work.selectRandomCreator, [0]],
                [steps.new_work.enterCreatorContribution, [0, 20]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(4.1)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 20]],
                [steps.new_work.selectRandomShellWorkCreator, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.enterNewShellWork, [1, 'TEST SHELL WORK ' + randomId(4.2)]],
                [steps.new_work.enterComponentWorkAllocation, [1, 20]],
                [steps.new_work.selectRandomShellWorkCreator, [1, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [1, 0, 100]],
                [steps.new_work.enterNewShellWork, [2, 'TEST SHELL WORK ' + randomId(4.3)]],
                [steps.new_work.enterComponentWorkAllocation, [2, 20]],
                [steps.new_work.selectRandomShellWorkCreator, [2, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [2, 0, 100]],
                [steps.new_work.ensureTotalContributionTooLowMessageIsDisplayed],
                [steps.new_work.enterNewShellWork, [3, 'TEST SHELL WORK ' + randomId(4.5)]],
                [steps.new_work.enterComponentWorkAllocation, [3, 20]],
                [steps.new_work.selectRandomShellWorkCreator, [3, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [3, 0, 100]],
                [steps.new_work.validateTotalContribution],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
                [steps.work.validateComponentWorkId, [1]],
                [steps.work.validateComponentWorkName, [1]],
                [steps.work.validateComponentWorkAllocation, [1]],
                [steps.work.clickShowComponentWorkDetailsButton, [1]],
                [steps.work.validateShellWorkCreatorName, [1, 0]],
                [steps.work.validateShellWorkCreatorContribution, [1, 0]],
                [steps.work.validateComponentWorkId, [2]],
                [steps.work.validateComponentWorkName, [2]],
                [steps.work.validateComponentWorkAllocation, [2]],
                [steps.work.clickShowComponentWorkDetailsButton, [2]],
                [steps.work.validateShellWorkCreatorName, [2, 0]],
                [steps.work.validateShellWorkCreatorContribution, [2, 0]],
                [steps.work.validateComponentWorkId, [3]],
                [steps.work.validateComponentWorkName, [3]],
                [steps.work.validateComponentWorkAllocation, [3]],
                [steps.work.clickShowComponentWorkDetailsButton, [3]],
                [steps.work.validateShellWorkCreatorName, [3, 0]],
                [steps.work.validateShellWorkCreatorContribution, [3, 0]],

                [steps.base.useBlankEntityDataSlot, ['work', 5]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(5)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Composite of Samples']],
                [steps.new_work.selectRandomCreator, [0]],
                [steps.new_work.enterCreatorContribution, [0, 65]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(5.1)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 5]],
                [steps.new_work.selectRandomShellWorkCreator, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.enterNewShellWork, [1, 'TEST SHELL WORK ' + randomId(5.2)]],
                [steps.new_work.enterComponentWorkAllocation, [1, 6]],
                [steps.new_work.selectRandomShellWorkCreator, [1, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [1, 0, 100]],
                [steps.new_work.enterNewShellWork, [2, 'TEST SHELL WORK ' + randomId(5.3)]],
                [steps.new_work.enterComponentWorkAllocation, [2, 7]],
                [steps.new_work.selectRandomShellWorkCreator, [2, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [2, 0, 100]],
                [steps.new_work.enterNewShellWork, [3, 'TEST SHELL WORK ' + randomId(5.5)]],
                [steps.new_work.enterComponentWorkAllocation, [3, 8]],
                [steps.new_work.selectRandomShellWorkCreator, [3, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [3, 0, 100]],
                [steps.new_work.ensureTotalContributionTooLowMessageIsDisplayed],
                [steps.new_work.enterNewShellWork, [4, 'TEST SHELL WORK ' + randomId(5.6)]],
                [steps.new_work.enterComponentWorkAllocation, [4, 9]],
                [steps.new_work.selectRandomShellWorkCreator, [4, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [4, 0, 100]],
                [steps.new_work.validateTotalContribution],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
                [steps.work.validateComponentWorkId, [1]],
                [steps.work.validateComponentWorkName, [1]],
                [steps.work.validateComponentWorkAllocation, [1]],
                [steps.work.clickShowComponentWorkDetailsButton, [1]],
                [steps.work.validateShellWorkCreatorName, [1, 0]],
                [steps.work.validateShellWorkCreatorContribution, [1, 0]],
                [steps.work.validateComponentWorkId, [2]],
                [steps.work.validateComponentWorkName, [2]],
                [steps.work.validateComponentWorkAllocation, [2]],
                [steps.work.clickShowComponentWorkDetailsButton, [2]],
                [steps.work.validateShellWorkCreatorName, [2, 0]],
                [steps.work.validateShellWorkCreatorContribution, [2, 0]],
                [steps.work.validateComponentWorkId, [3]],
                [steps.work.validateComponentWorkName, [3]],
                [steps.work.validateComponentWorkAllocation, [3]],
                [steps.work.clickShowComponentWorkDetailsButton, [3]],
                [steps.work.validateShellWorkCreatorName, [3, 0]],
                [steps.work.validateShellWorkCreatorContribution, [3, 0]],
                [steps.work.validateComponentWorkId, [4]],
                [steps.work.validateComponentWorkName, [4]],
                [steps.work.validateComponentWorkAllocation, [4]],
                [steps.work.clickShowComponentWorkDetailsButton, [4]],
                [steps.work.validateShellWorkCreatorName, [4, 0]],
                [steps.work.validateShellWorkCreatorContribution, [4, 0]],

                [steps.base.useBlankEntityDataSlot, ['work', 6]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(6)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Composite of Samples']],
                [steps.new_work.selectRandomCreator, [0]],
                [steps.new_work.enterCreatorContribution, [0, 64.147]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(6.1)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 5.123]],
                [steps.new_work.selectRandomShellWorkCreator, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.enterNewShellWork, [1, 'TEST SHELL WORK ' + randomId(6.2)]],
                [steps.new_work.enterComponentWorkAllocation, [1, 10.321]],
                [steps.new_work.selectRandomShellWorkCreator, [1, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [1, 0, 100]],
                [steps.new_work.enterNewShellWork, [2, 'TEST SHELL WORK ' + randomId(6.3)]],
                [steps.new_work.enterComponentWorkAllocation, [2, 20.409]],
                [steps.new_work.selectRandomShellWorkCreator, [2, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [2, 0, 100]],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],
                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkId, [0]],
                [steps.work.validateComponentWorkName, [0]],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
                [steps.work.validateComponentWorkId, [1]],
                [steps.work.validateComponentWorkName, [1]],
                [steps.work.validateComponentWorkAllocation, [1]],
                [steps.work.clickShowComponentWorkDetailsButton, [1]],
                [steps.work.validateShellWorkCreatorName, [1, 0]],
                [steps.work.validateShellWorkCreatorContribution, [1, 0]],
                [steps.work.validateComponentWorkId, [2]],
                [steps.work.validateComponentWorkName, [2]],
                [steps.work.validateComponentWorkAllocation, [2]],
                [steps.work.clickShowComponentWorkDetailsButton, [2]],
                [steps.work.validateShellWorkCreatorName, [2, 0]],
                [steps.work.validateShellWorkCreatorContribution, [2, 0]],
            ]
        },
        {
            name: 'Edit a COS composite work with shell works',
            tags: [],
            steps: [
                [steps.base.useBlankEntityDataSlot, ['work', 7]],

                [steps.new_work.goToNewWorkPage],
                [steps.new_work.enterPrimaryWorkTitle, ['TEST COMPOSITE WORK ' + randomId(7)]],
                [steps.new_work.clickCompositeWorkCheckbox],
                [steps.new_work.selectCompositeWorkType, ['Composite of Samples']],
                [steps.new_work.selectRandomCreator, [0]],
                [steps.new_work.enterCreatorContribution, [0, 50]],
                [steps.new_work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(7.1)]],
                [steps.new_work.enterComponentWorkAllocation, [0, 50]],
                [steps.new_work.expectShellWorkTitleToMatchEnteredOne, [0]],
                [steps.new_work.selectRandomShellWorkCreator, [0, 0]],
                [steps.new_work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.new_work.optToIncludeWorkOnWebsite, [false]],
                [steps.new_work.saveWork],
                [steps.new_work.validateSaveWorkRedirection],

                [steps.base.sleep, [100]],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.deleteComponentWork, [0]],
                [steps.work.expectComponentWorkDeletionConfirmationPopUpToBeDisplayed],
                [steps.work.confirmComponentWorkDeletion],
                [steps.work.enterNewShellWork, [0, 'TEST SHELL WORK ' + randomId(7.2)]],
                [steps.work.enterComponentWorkAllocation, [0, 50]],
                [steps.work.expectShellWorkTitleToMatchEnteredOne, [0]],
                [steps.work.selectRandomShellWorkCreator, [0, 0]],
                [steps.work.enterShellWorkCreatorContribution, [0, 0, 100]],
                [steps.work.saveCreators],

                [steps.base.refreshPage],
                [steps.work.hoverCreatorNamesContainer],
                [steps.work.editCreators],
                [steps.work.validateComponentWorkAllocation, [0]],
                [steps.work.clickShowComponentWorkDetailsButton, [0]],
                [steps.work.validateShellWorkCreatorName, [0, 0]],
                [steps.work.validateShellWorkCreatorContribution, [0, 0]],
            ]
        },
    ];

module.exports = {
    commonFeatureTags: ['define-composite-shell-works'],
    feature: feature,
    beforeFeature: beforeFeature
};
